version: '3.4'

services:
  fasticule-webapp:
    build: .
    expose:
      - 8001
    labels:
      - traefik.enable=true
      - traefik.http.routers.myapp.tls=true
      - traefik.http.routers.myapp.rule=Host("localhost")
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.traefik=true"
    ports:
      # Fasticule web app port
      - "8001:8001"
      # HTTPS / SSL port
      - "443:443"
      # The Traefik Web UI port
      - "8080:8080"
    volumes:
     - ./service/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
     - ./service/traefik/config.yml:/etc/traefik/config.yml:ro
     - ./localhost-cert:/etc/certs:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro